AWSTemplateFormatVersion: 2010-09-09
Description: >
  This template instantiates a security role in the target account which
  can be assumed only from the security account
Parameters:
  Principal:
    Type: String
    Description: ARN of Principal with privilege to assume this role
Resources:
  SecurityRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              AWS:
                Ref: Principal
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      MaxSessionDuration: 43200
      Path: /security/
      RoleName: security-admin
