AWSTemplateFormatVersion: 2010-09-09
Description: >
  This template will create a standard SQS queue with empty SQS Policy
Parameters:
  QueueName:
    Type: String
    Description: Name of queue
Resources:
  CodeBuildSQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 0
      MaximumMessageSize: 1024
      MessageRetentionPeriod: 86400
      QueueName: !Ref QueueName
      ReceiveMessageWaitTimeSeconds: 5
      VisibilityTimeout: 60
Outputs:
  CodeBuildSQSQueueURL:
    Description: The URL of the SQS queue
    Value: !Ref CodeBuildSQSQueue
    Export:
      Name: !Sub '${QueueName}-SQSQueueURL'
  CodeBuildSQSQueueArn:
    Description: The Arn of the SQS Queue
    Value: !GetAtt CodeBuildSQSQueue.Arn
    Export:
      Name: !Sub '${QueueName}-SQSQueueArn'
