AWSTemplateFormatVersion: 2010-09-09
Description: >
  This template instantiates an EventBridge rule to trigger CodeBuild on a CodeCommit event
Parameters:
  RuleName:
    Type : String
    Description: Name of event rule
  CodeBuildArn:
    Type: String
    Description: Arn of CodeBuild project to trigger
  CodeCommitBranch:
    Type: String
    Description: Branch in repository to trigger from
Resources:
  EventRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: events-codebuild
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - codebuild:StartBuild
                Resource: !Ref CodeBuildArn
      RoleName: event-role-codebuild-kriation
  Event:
    Type: AWS::Events::Rule
    Properties:
      Description: Rule to trigger a CodeBuild project on a CodeCommit event
      EventPattern:
        source:
          - 'aws.codecommit'
        detail-type:
          - 'AWS API Call via CloudTrail'
        detail:
          eventName:
            - 'GitPush'
          requestParameters:
            references:
              ref:
                - !Sub 'refs/heads/${CodeCommitBranch}'
      Name: !Sub 'event-${RuleName}'
      Targets:
        - Arn: !Ref CodeBuildArn
          Id: !Sub 'target-${RuleName}'
          RoleArn: !GetAtt EventRole.Arn
