AWSTemplateFormatVersion: 2010-09-09
Description: >
  This template instantiates a programmatic user, group, and associated policy
  to provide read-only access to a specific S3 bucket programmatically.
Parameters:
  UserName:
    Type: String
  GroupName:
    Type: String
  S3BucketName:
    Type: String
Resources:
  S3AccessGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Ref GroupName
      Policies:
        - PolicyName: S3ReadAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                - s3:ListBucket
                - s3:GetBucketLocation
                - s3:GetObject
                - s3:GetObjectVersion
                Resource:
                - !Sub 'arn:aws:s3:::${S3BucketName}'
                - !Sub 'arn:aws:s3:::${S3BucketName}/*'
  S3AccessUser:
    Type: AWS::IAM::User
    Properties:
      Groups: 
        - !Ref GroupName
      UserName: !Ref UserName
