AWSTemplateFormatVersion: 2010-09-09
Description: >
  This template instantiates a CodeCommit repository
Parameters:
  RepositoryName:
    Type: String
    Description: Name of the repository
  RepositoryDescription:
    Type: String
    Description: Purpose of the repository
Resources:
  Repository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      RepositoryDescription: !Ref RepositoryDescription
Outputs:
  RepoCloneURLHTTP:
    Description: The HTTP clone URL for the repository
    Value: !GetAtt Repository.CloneUrlHttp
    Export:
      Name: !Sub 'RepoURL-${RepositoryName}'
  RepoCloneURLSSH:
    Description: The SSH clone URL for the repository
    Value: !GetAtt Repository.CloneUrlSsh
  RepoARN:
    Description: The ARN for the repository
    Value: !GetAtt Repository.Arn
    Export:
      Name: !Sub 'ARN-${RepositoryName}'
