AWSTemplateFormatVersion: 2010-09-09
Description: >
  This template instantiates an ECR repository for container images with an
  attached lifecycle policy
Parameters:
  repositoryName:
    Type: String
    Description: Name of the repository that will contain images
  lifecyclePolicy:
    Type: String
    Description: >
      The lifecycle policy to associate to this repository in JSON
      format.
Resources:
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      LifecyclePolicy:
        LifecyclePolicyText: !Ref lifecyclePolicy
      RepositoryName: !Ref repositoryName
Outputs:
  RepositoryARN:
    Description: The ARN of the created repository
    Value: !GetAtt Repository.Arn
    Export:
      Name: !Sub 'repo-ecr-${repositoryName}'
